#!/usr/bin/env node

/**
 * Generate build info file with current timestamp.
 * Run as part of the build process.
 */

import { writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const buildTime = new Date().toISOString();

const content = `// Auto-generated by scripts/generateBuildInfo.ts — do not edit
export const BUILD_TIME = '${buildTime}';
`;

const outPath = resolve(__dirname, '..', 'src', 'shared', 'buildInfo.ts');
writeFileSync(outPath, content, 'utf-8');
console.log(`Build info generated: ${buildTime}`);
